### ISSUE TITLE
Tests failing due to LinearAlgebraForCAP not being loaded as a dependency of FreydCategoriesForCAP anymore

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/HigherHomologicalAlgebra#101]
If you decide to load LinearAlgebraForCAP in 100_LoadPackages.tst, please do so using PackageJanitor to make sure things are in sync :-)

**Comment by zickgraf** [comment]
It seems like you have added `LinearAlgebraForCAP` in e76967f4188e295445e42a15a506b28d9aef4ab8. Could you also update PackageJanitor accordingly and apply it once to make sure things are in sync? (I think PackageJanitor has not been applied for some time to the repo, so many changes are expected)

**Comment by kamalsaleh** [comment]
Thank you for reporting the issue. It has been resolved in a later commit:  I changed the `underlying_category` to `CategoryOfRows(k)`
https://github.com/homalg-project/HigherHomologicalAlgebra/blob/3a9f85ef8c760bd5eb7b52153412cd7039d59b92/ComplexesCategories/tst/proj_inj_resolutions_in_vector_spaces.tst#L1-L14

I have also already applied `PackageJanitor` https://github.com/homalg-project/HigherHomologicalAlgebra/commit/122014dc7c76af66b332d4f73e5077715cee4042.
