### ISSUE TITLE
CI is failing because FunctorCategories now depends on PreSheaves

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/HigherHomologicalAlgebra#127]
but PreSheaves (i.e. CategoricalTowers) is not cloned in the CI.

**Comment by zickgraf** [comment]
Addendum: You can either clone CategoricalTowers or the subsplit PreShaves. I suggest cloning PreSheaves. This way the CI fails if one suddenly pulls in a new dependency.

**Comment by kamalsaleh** [comment]
Thank you Fabian!
