### ISSUE TITLE
CI failing due to LaTeX errors in the documentation of StableCategories

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/HigherHomologicalAlgebra#132]
These errors we not caught until now due to a bug in ReleaseTools when using "dash" as a shell (https://github.com/gap-system/ReleaseTools/pull/99). They are caught now because I have switched "dash" to "bash" in https://github.com/homalg-project/gap-docker-base/commit/2e48b44afe94e8236d87f1e8a7b8a76de990d149.

**Comment by kamalsaleh** [comment]
Thank you! The tests pass now because the latex erros have been addressed.
