### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/HigherHomologicalAlgebra#135]
@mohamed-barakat It looks like your changes have affected HigherHomlogicalAlgebra after all:
```
Error, the underlying category must be equipped with a Hom-Structure
```

**Comment by kamalsaleh** [comment]
thank you Fabian, after mohamed's changes the FreydCategory over a polynomial ring knows it is equipped with Hom-Structure.

closed by https://github.com/homalg-project/HigherHomologicalAlgebra/pull/137

**Comment by zickgraf** [comment]
For future reference: https://github.com/homalg-project/CAP_project/pull/1258 was also part of the fix, I think.
