### ISSUE TITLE
README is missing at least one dependency (PreSheaves)

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/HigherHomologicalAlgebra#171]
Maybe it would be better to instead suggest to install all of https://github.com/homalg-project/CategoricalTowers in one go?

(I find it rather confusing that now many homalg packages live in two places, e.g. there is both  https://github.com/homalg-project/CategoricalTowers/tree/master/PreSheaves and https://github.com/homalg-project/PreSheaves - the latter is apparently derived from the former. But what's the point of these subsplits?

**Comment by mohamed-barakat** [comment]
Your question is justified. The original idea behind the subsplits was to demonstrate (and constantly verify) that this project is not monolithic and that external contributions are possible. We went for the mono-repo to simplify our own workflow, but it is, strictly speaking, not a necessity. Maybe we could convey this message more explicitly and delete the subsplits.

**Comment by mohamed-barakat** [comment]
Apart from that, I am so grateful that you are pulling these packages, although they are undeposited :)
