### ISSUE TITLE
Dependency on GradedModulePresentations

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/HigherHomologicalAlgebra#2]
The package `GradedModulePresentations` should probably be listed as a dependency of `DerivedCategories`, since commands like `GradedFreeLeftPresentation` are used within the file `DerivedCategories/gap/OtherQPATweaks.gi`, which leads to an error if `BBGG` is not loaded.

**Comment by kamalsaleh** [comment]
The file `DerivedCategories/gap/OtherQPATweaks.gi` has been removed :-) --> closing the issue.
