### ISSUE TITLE
return_type of HomotopyMorphisms

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/HigherHomologicalAlgebra#25]
I'm currently trying to compose a list of valid return_types in the method record. `HomotopyMorphisms` has the return type `[ IsZFunction ]`. Are the list brackets intended or should the return type actually be `IsZFunction` (without list brackets)?

**Comment by kamalsaleh** [comment]
I believe they aren't. Since the brackets are not necessary, I will remove them.
