### ISSUE TITLE
Synonyms

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/HigherHomologicalAlgebra#4]
I strongly advise against the usage of synonyms as you do for (at least) the following variables:

`id, hom, iota, pi`

1) Usually, commands in GAP start with a capital letter
2) Usually, variable names in GAP start with a small letter
3) Usually, variable names in an interactive GAP session are short

Thus, declaring `id` as a synonym for `IdentityMorphism` is counterproductive as it violates 1) and prohibits the usage of `id` as a variable name in an interactive session, which right now leads to errors in the tests of `FreydCategoriesForCAP`. Moreover, the right place for such a declaration would be in the `CAP` package.

**Comment by kamalsaleh** [comment]
Opps, sorry for causing the errors in the tests :| . The reason for this was doing a LOT of experiments where it was counterproductive each time to write `IdentityMorphism`, `MorphismIntoStandardConeObjects(=iota)`, `ForwardPostnikovSystemAt(=fpkv)` etc.. . I will install a function that declares such synonyms and use only in interactive sessions.

**Comment by sebastianpos** [comment]
Thank you :)
