### ISSUE TITLE
Tests failing due to changes to FunctorCategories

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/HigherHomologicalAlgebra#64]
@mohamed-barakat Could you update the tests for the changes to FunctorCategories?

**Comment by zickgraf** [comment]
I would suggest not waiting with the fixes for the CI: having a broken CI for several days means potentially having to bisect through lots of changes if other bugs have sneaked in unnoticed in the meantime, means potentially missing broken packages when looking at https://homalg-project.github.io/docs/CAP_project-based/, and looks very bad for external contributors.

**Comment by mohamed-barakat** [comment]
This is on my short term to-do list :)

**Comment by zickgraf** [comment]
@mohamed-barakat I think the original issue was fixed by #65. However, the tests in `StableCategories` are failing again since https://github.com/homalg-project/FunctorCategories/commit/81275b02589f3e7752a81e7b271409c673d8f944

**Comment by zickgraf** [comment]
Would it make sense to test HigherHomologicalAlgebra in the CI of FunctorCategories? In general I'm against mangling the tests too much, but in this case it would have prevented two problems in two weeks, so maybe it would be worth it in this case.
